const en = {
  brand: 'Safarwise',
  tagline: 'Travel OS for the Muslim Journey',
  heroLead: 'We build technology that brings trust, speed, and calm back into travel. AI where it helps — robust processes where it counts.',
  ctaExplore: 'Explore the ecosystem',
  ctaStory: 'Read our story',
  whyTitle: 'Why Safarwise?',
  whyP1: 'Travel for millions of Muslims has unique needs: halal-friendly options, timely Umrah logistics, transparent pricing and trusted partners. Today’s market is fragmented and slow.',
  whyP2: 'Safarwise unifies it into a single Travel Operating System — a set of tools that work together. We combine data, AI assistants and streamlined workflows so agencies and travelers reach the right decision faster.',
  missionTitle: 'Our mission',
  missionP: 'Make Muslim travel radically simpler — from discovery to booking to aftercare — with technology that feels human and runs on discipline.',
  missionBul1: 'Faster replies, fewer errors',
  missionBul2: 'Transparent prices and options',
  missionBul3: 'Tools that move agencies forward',
  ecoTitle: 'Our ecosystem',
  ecoIntro: 'Powerful tools that together form the Travel OS.',
  storyTitle: 'Our story',
  storyP1: 'It started with one frustration: agencies stuck in tools, customers waiting weeks for a clear proposal. We chose a different path.',
  storyP2: 'We built small helpers first — a WhatsApp agent here, a CRM view there. It grew into a complete system. Today, Safarwise is a Travel OS that helps agencies focus and travelers smile. We’re just getting started, inshaa’Allah.',
  quote: 'Technology is good only when it restores trust and calm.',
  contactCTA: 'Email or WhatsApp us — no forms.',
  contactEmail: 'Email',
  contactWhatsApp: 'WhatsApp',
  investors: 'Investors',
  partners: 'Partners',
  tools: 'Tools',
  navEcosystem: 'Ecosystem',
  navStory: 'Our story',
  navContact: 'Contact',
  navInvestors: 'Investors',
  navPartners: 'Partners',
  moreInfo: 'More info',
  tool: {
    labeeb: {title:'Labeeb AI',desc:'AI Umrah Planner for personalized composition & advice.'},
    travelycs: {title:'Travelycs Desk',desc:'Backoffice CRM for travel agencies, built for Umrah & Muslim travel.'},
    concierge: {title:'AI Hotel Concierge',desc:'24/7 guest service for hotels in Makkah & Madinah, WhatsApp-first.'},
    smarthub: {title:'Smart Hub',desc:'API connectivity with airlines, DMCs and suppliers — one place, one truth.'}
  }
};
export default en;
